### ISSUE TITLE
Feature Request: Check whether tests are included in PyPI

### ISSUE THREAD

**Issue by jgarte** [davep/pispy#1]
Hi,

What do you think if `pispy` had a feature where it can quickly compare whether tests are included in PyPI.

Use case:

When packaging Python software for [GNU Guix](https://guix.gnu.org/) we always prefer to package the upstream source that includes the Python tests in the repository so that we may run them to make sure nothing has broken with our packaged dependencies.

**Comment by jgarte** [comment]
It's not last time I checked. Out of scope?

**Comment by davep** [comment]
Given that this is a simple tool to show data from the PyPi, I think I'd be inclined to say yes, not really in scope. I can imagine there's a *lot* of different ways someone may implement their tests and I wouldn't want that to overtake this simple bit of code.

Sounds like something perhaps better done as a CLI tool? Something you run, pass the name of a package, it goes and grabs it and looks around inside the package for signs of tests and then reports back.

**Comment by jgarte** [comment]
So maybe something like this rough code:

https://git.sr.ht/~whereiseveryone/compost/tree/master/item/ls-pypi-tar.py

**Comment by davep** [comment]
Aye, I'd imagine that would be the heart of such a tool.

**Comment by jgarte** [comment]
Closing this ticket in favour of going to fix the linked script some more.
