### ISSUE TITLE
Improve displayed metadata

### ISSUE THREAD

**Issue by pawamoy** [davep/pispy#2]
Nice project! I very often check out projects on pypi.org, this could saved a few dozen clicks per day!

I tried it on my Griffe project. Here is some feedback.

- It seems PISpy hardcodes some field names, expecting to find them in the metadata. I say this because I notice a lot of fields which are `None`: Bug Track URL, Documentation URL, Download URL, Homepage. This package does have URLs for all these, just named differently. And they do show up afterwards, so maybe don't expect any field, and just show the ones that exist/have a non-null value?
- Email appears twice, once at the top with the right value, a second time towards the bottom with `None`.
- Author appears as `None`. That's expected based on PEP 621, though maybe it could be hidden, and/or both Author and Email fields could be merged as "Authors / Emails".
- Not sure why, but License appears as `None`, while PyPI correctly shows `ISC`.
- Again, maybe hide `None` fields, such as Maintainer, Platform, and Yanked Reason if Yanked if false.

![pispy](https://github.com/davep/pispy/assets/3999221/e5d4c982-a6b3-4818-8910-daab0d0126c8)

**Comment by davep** [comment]
Thanks! All good points. As you may have noticed this was one of the first projects I did with Textual, as [a dogfooding exercise](https://textual.textualize.io/blog/2022/12/08/be-the-keymaster/#pispy) and it's showing up that it's a) a bit old now and b) a bit of a quick hack. I have it on my hopefully near-term todo list to do a ground-up rewrite of it.

I'll keep all of these suggestions in mind.

**Comment by pawamoy** [comment]
Yes, I exactly found it like that :smile: Of course, I don't expect immediate changes to the tool, I'm happy to just leave this feedback here for when someone has the will and capacity to act on it :slightly_smiling_face: Thanks for your quick reply!

**Comment by davep** [comment]
Very much appreciate it. I've got a wee bit of time off coming up soon and had actually penciled in coming back to this and giving it a revamp.

**Comment by davep** [comment]
Heading my way back here soon, [as promised here](https://www.youtube.com/watch?v=CepsN8TDq1E).
